#### Basic overview of encoding --> OneHotEncoding(nominal data),Ordinal Encoder(order),LabelEncoder

In [2]:
import pandas as pd
import sklearn

In [3]:
bank=pd.read_csv('Bank_Marketing_Original_Data.csv')

In [4]:
bank

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

#### ordinal data ---> tertiary > secondary > primary > others
#### so encoding will be done as 3 2 1 0

In [5]:
bank['Education'].value_counts()

Education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
ordinal_data=bank[['Education']]
oe=OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']])

In [8]:
oe.fit_transform(ordinal_data)

array([[3.],
       [2.],
       [2.],
       ...,
       [2.],
       [2.],
       [2.]], shape=(45211, 1))

#### Target column is often referred as Label,so  Label Encoding should be performed on it

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [10]:
Target_Data=bank[['TARGET']]
le.fit_transform(Target_Data)

c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))

In [11]:
from sklearn.preprocessing import OneHotEncoder
oe = OneHotEncoder()

In [12]:
nominal_data=bank[['Job','Marital','Default','Balance','Housing','Loan','contact','Month','poutcome']]
nominal_data=oe.fit_transform(nominal_data)

#### Column Transformer -->  In the previous approach we say that we did encoding in a naive way and by spliting the columns and we nned to add them to again reflect in the dataframe and that isa time taking process 
### so we use the column transformer performs the operations on the dataframe without splitting them 
### simple imputer can also used by the means of column transformer

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
col_trans=ColumnTransformer(transformers=[('t1',OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']]),['Education']),('t2',OneHotEncoder(),['Job','Marital','Default','Balance','Housing','Loan','contact','Month','poutcome'])],remainder='passthrough')

In [15]:
X=bank.iloc[:,:-1]

In [16]:
X

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [17]:
Y=bank[['TARGET']]

In [18]:
X_Transformed=col_trans.fit_transform(X)

In [19]:
le=LabelEncoder()
le.fit_transform(Y)

c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))

In [20]:
bank.columns

Index(['Age', 'Job', 'Marital', 'Education', 'Default', 'Balance', 'Housing',
       'Loan', 'contact', 'Day', 'Month', 'Duration', 'Campaign', 'Pdays',
       'Previous', 'poutcome', 'TARGET'],
      dtype='str')